Fix the Bukkit component serializer by setting the correct JSONOptions according to the server version
KyoriPowered/adventure-platform pull request #197
Opened 2024-12-02 17:18 UTC by MemencioPerez

Fixes #150

2024-12-10 04:30 UTC, zml2008 requested changes
1) not a full upgrade to newer adventure versions
2) get the data version from the game, don't do this halfassed garbage

2024-12-10 18:17 UTC, MemencioPerez commented
> 1. not a full upgrade to newer adventure versions
> 2. get the data version from the game, don't do this halfassed garbage

I'm sorry I did it, I wasn't very enlightened at the time. Does it work better for you to use Bukkit.getUnsafe() to get the version value of the data or should I use NMS/Reflection?

2024-12-10 18:25 UTC, MemencioPerez commented
And regarding it not being a full upgrade, do you mean that I should upgrade the rest of the Bukkit platform classes or what specifically?

2025-02-09 19:43 UTC, zml2008 commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitComponentSerializer.java
> +  private static final int DATA_VERSION = Bukkit.getUnsafe().getDataVersion();
Did this method exist in 1.8?

2025-02-09 23:14 UTC, MemencioPerez commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitComponentSerializer.java
> +  private static final int DATA_VERSION = Bukkit.getUnsafe().getDataVersion();
No, it was introduced in version 1.13. Anyway, I think it would be enough to check if the UnsafeValues class has this method before calling it, because we are only interested in the Data Version from version 1.16.5, and the UnsafeValues class exists since version 1.7.2.

2025-05-10 22:46 UTC, zml2008 commented
Superceded by #206

2025-05-10 22:46 UTC, closed without merging