Add per-viewer Component rendering
KyoriPowered/adventure-platform pull request #48
Opened 2021-04-11 00:32 UTC by Electroid

There are many situations where developers need to modify a `Component` that is passed through an `Audience` to be customized for that particular viewer.

Each viewer is given an `AudienceIdentity`.

```java
public interface AudienceIdentity extends Identity {
  UUID uuid(); // UUID(0, 0) for non-players
  Locale locale();
  @Nullable String world();
  @Nullable String server();
  boolean player();
  boolean console();
  boolean permission(final String key);
}
```

Then, when building a `AudienceProvider`, developers can specify a `ComponentRenderer< AudienceIdentity>` to customize `Component`s that are passed through each `Audience`.

```java
Plugin plugin;
BukkitAudienceProvider provider = BukkitAudienceProvider.builder(plugin)
   .componentRenderer(new ComponentRenderer<AudienceIdentity>() {
      @Override
      public Component render(final Component component, final AudienceIdentity context) {
        final Player viewer = Bukkit.getPlayer(context.uuid());
        if(viewer == null) return component;
        return component.replaceText(TextReplacementConfig.builder()
          .matchLiteral("@" + viewer.getName())
          .replacement(LegacyComponentSerializer.legacySection().deserialize(viewer.getDisplayName()))
          .build());
      }
    })
  .build();

provider.server().sendMessage(text("Hello @ElectroidFilms!"));
```

This is an alternative implementation to #42. The key challenge with that is you can only customize `Component`s by `Locale`, where here you can customize it by locale, viewer, console, or anything else.

2021-04-12 23:24 UTC, applenick commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitIdentity.java
> +      }
I believe this should be outside of the null player check. Otherwise `locale` will be null if the CommandSender is a `ConsoleCommandSender`

2021-06-04 12:48 UTC, kezz requested changes
I think this is a good idea, it makes the platform builds quite powerful. However, I do have a few concerns/comments.

Now that audiences have pointers, does this not make the `AudienceIdentity` class obsolete? Stuff like locale, world, etc. could easily be obtained from pointers. If the partitioning is a desired feature (e.g. to reduce duplicate rendering) this could be done using a predicate on an audience instead of a hashcode, or something similar to this.

In fact, I think that the `AudienceIdentity` class is rather confusing. If it exists to allow partitioning, why does it provide individual elements such as UUID, especially considering that these are non-null? If it exists to allow an abstraction around audience members, why doesn't it provide the ability to get the actual audience member in the renderer function?

2021-06-04 12:48 UTC, kezz commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudience.java
> +  BukkitAudience(final @NonNull Plugin plugin, final FacetAudienceProvider<?, ?> provider, final @NonNull Collection<CommandSender> viewers) {
```suggestion
  BukkitAudience(final @NonNull Plugin plugin, final @NonNull FacetAudienceProvider<?, ?> provider, final @NonNull Collection<CommandSender> viewers) {
```

2021-06-04 12:48 UTC, kezz commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudiences.java
> +   * @since 4.5.0
Should this, and others, not be `4.0.0`?

2021-06-04 12:48 UTC, kezz commented on platform-facet/src/main/java/net/kyori/adventure/platform/facet/FacetAudienceProvider.java
> +  protected final ToIntFunction<AudienceIdentity> partitionFunction;
Is this partition function actually used anywhere?

2021-09-06 21:50 UTC, zml2008 commented
Superseded by #57

2021-09-06 21:50 UTC, closed without merging