platform-bukkit: fix ViaVersion softDepend occurring too late
KyoriPowered/adventure-platform pull request #80
Opened 2022-01-14 22:14 UTC by TehBrian

2022-01-26 06:04 UTC, zml2008 requested changes

2022-01-26 06:04 UTC, zml2008 commented on platform-bukkit/src/main/java/net/kyori/adventure/platform/bukkit/BukkitAudiencesImpl.java
> +    this.softDepend("ViaVersion");
This doesn't need to run on every audience creation -- maybe put it in the computeIfAbsent lambda within the build() method of the BukkitAudiences.Builder?

2022-01-26 09:44 UTC, kezz commented
Would it not be easier to just lazily initialise the empty audience? It's the creation of the empty audience that is causing this issue after all.

2022-01-26 16:43 UTC, TehBrian commented
Chucking softDepend in BukkitAudiences.Builder would fix the root problem (creating BukkitAudiencesImpl before calling softDepend) rather than the symptom, but both fixes would work. Let me know what fix to implement and I'll update the pr.

2022-02-03 20:37 UTC, kezz commented
@TehBrian would you mind making *both* changes? So, moving the soft depend method *and* making the empty audience lazily initialised? Sorry for the annoyance :p

2022-02-04 03:04 UTC, zml2008 approved these changes

2022-02-04 03:08 UTC, merged